// 50 запросов, покрывающих конструкции программы (главы 2-14)
export const QUERIES = [
  'select * from book',
  'select title, price * 0.9 as sale from book',
  "select 'Привет' as x, b.title from book b",
  'select * from book where price > 500 and (pages < 300 or author_id is null)',
  'select * from book where price between 400 and 900',
  "select * from book where title ilike '%python%'",
  'select * from book where author_id in (1, 3, 5)',
  'select * from book where author_id is distinct from 1',
  'select coalesce(price, 0), nullif(pages, 0) from book',
  'select * from book order by price desc nulls last, title',
  'select * from book order by 2',
  'select * from book limit 3 offset 2',
  'select * from book order by price fetch first 3 rows with ties',
  'select distinct author_id from book',
  'select distinct on (category_id) category_id, title, price from book order by category_id, price desc',
  "select title, case when price > 1000 then 'дорого' when price > 500 then 'средне' else 'дёшево' end from book",
  'select * from (values (1, 2), (3, 4)) as t(a, b)',
  'select g from generate_series(1, 5) g',
  'select b.title, a.name from book b join author a on a.author_id = b.author_id',
  'select b.title, a.name from book b join author a using (author_id)',
  'select * from book b left join author a using (author_id)',
  'select * from book b right join author a using (author_id)',
  'select * from book b full join author a using (author_id)',
  'select * from author cross join book_category',
  'select e.name, m.name from employee e left join employee m on m.employee_id = e.manager_id',
  'select * from orders o join order_item oi using (order_id) join book b using (book_id)',
  'select * from book natural join author',
  'select * from author a where exists (select 1 from book b where b.author_id = a.author_id)',
  'select * from author a where not exists (select 1 from book b where b.author_id = a.author_id)',
  'select * from author where author_id not in (select author_id from book where author_id is not null)',
  'select a.name, t.title from author a cross join lateral (select title from book b where b.author_id = a.author_id order by price desc limit 1) t',
  'select count(*), count(price), sum(price), avg(price), min(price), max(price) from book',
  'select author_id, count(*) from book group by author_id',
  'select author_id, count(*) from book group by author_id having count(*) > 1',
  'select category_id, count(*) filter (where price > 500), string_agg(title, \', \') from book group by category_id',
  'select category_id, author_id, count(*) from book group by rollup (category_id, author_id)',
  'select title, (select name from author a where a.author_id = b.author_id) from book b',
  'select title from book union select name from author',
  'select author_id from author except select author_id from book',
  'with cheap as (select * from book where price < 500) select * from cheap',
  'with recursive t as (select employee_id, manager_id, 1 as lvl from employee where manager_id is null union all select e.employee_id, e.manager_id, t.lvl + 1 from employee e join t on e.manager_id = t.employee_id) select * from t',
  'select title, price, rank() over (partition by category_id order by price desc) from book',
  'select order_id, sum(qty) over (order by order_id rows between 1 preceding and current row) from order_item',
  "insert into author (name, country) values ('Лев Толстой', 'Россия') returning *",
  'update book set price = price * 1.1 where category_id = 3 returning book_id, price',
  'delete from review where rating < 3',
  "insert into customer (name, email, created_at) values ('X', 'anna@example.com', now()) on conflict (email) do update set name = excluded.name",
  'merge into book b using (values (1, 999)) s(id, p) on b.book_id = s.id when matched then update set price = s.p when not matched then do nothing',
  'create table t (id bigint generated always as identity primary key, name text not null unique, total numeric generated always as (id * 2) stored)',
  'alter table book add column isbn text, alter column pages set not null',
];
